#!/bin/sh

set -e

./portod stop 2>/dev/null || true

rm -f /var/log/portod.*

for g in porto porto-containers ; do
	getent group $g >/dev/null || groupadd $g
done

for u in porto-alice porto-bob; do
	id $u >/dev/null || useradd $u -G porto
done

uname -a
uptime
./portod version

./portod --discard --verbose start
