#!/bin/sh

FMT="#define GIT_TAG \"%s\"\n#define GIT_REVISION \"%s\"\n"
TAG="`git describe --match "v[0-9]*" --abbrev=7 HEAD 2>/dev/null`"
REV="`git rev-parse HEAD`"

if [ "`cat version.hpp`" != "`printf "$FMT" "$TAG" "$REV"`" ] ; then
	printf "$FMT" "$TAG" "$REV" > version.hpp
fi
