#!/bin/bash

TAG="$(git describe --match "v[0-9]*" --abbrev=7 HEAD 2>/dev/null)"
HASH="$(git log -1 "--format=format:const std::string GIT_REVISION = \"%H\";" HEAD)"
TEXT="${HASH}\nconst std::string GIT_TAG = \"$TAG\";"

TMP="GIT-VERSION-NEW"

echo -e "$TEXT" > $TMP
if [ ! "$(cat $TMP)" = "$(cat version.hpp)" ]; then
	mv $TMP version.hpp
else
	rm $TMP
fi
