#!/bin/sh

ver=`sed -nE 's#.*\((.*)\).*#\1#p;q' debian/changelog`

commit() {
	gbp dch --new-version $(echo ${ver} | perl -pe 's/^((\d*\D+)*)(\d+)$/$1.($3+1)/e') --distribution=unstable --urgency=low --ignore-branch
	ver=`sed -nE 's#.*\((.*)\).*#\1#p;q' debian/changelog`
    git add debian/changelog
    git commit -s -m "release: ${ver}"
	git tag -f -s "v${ver}" -m "release: ${ver}"
}

push() {
	git push origin
	git push origin -f v${ver}:v${ver}
}

pypi() {
    cd src/api/python/
    python setup.py sdist upload -r yandex
}

case "$1" in
all)
	commit
	push
;;
commit)
	commit
;;
push)
	push
;;
pypi)
	pypi
;;
"")
	echo "Usage: $0 all|commit|push|pypi"
;;
esac
