#!/bin/sh

set -e

if [ -z "$@" ]; then
	echo "Please specify tag message!"
	exit 1
fi

dch -i
version=v$(head -n1 debian/changelog | sed -e 's/[^(]*(\([^)]*\).*/\1/')
git commit -am "debian: release $version"
git tag -a $version -m "$@"
