#!/bin/sh
# postrm script
case "$1" in
    purge)
        groupdel porto
        if [ $? -ne 0 ]; then
            echo "Group 'porto' does not remove!"
        fi
        update-rc.d -f yandex-porto remove >/dev/null || exit $?
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
