#!/bin/sh
# postrm script
case "$1" in
    purge)
        update-rc.d -f yandex-porto remove >/dev/null || exit $?
    ;;
    upgrade)
        if [ -e "/etc/init/yandex-porto.conf" ]; then
            reload yandex-porto
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
