#!/bin/sh
# postinst script

case "$1" in
    configure)
        chown root:porto /usr/sbin/portoctl || exit 2
        update-rc.d yandex-porto start 90 2 3 4 5 .
        if [ -e "/etc/init/yandex-porto.conf" ]; then
            start yandex-porto
        fi
    ;;
    install|upgrade|abort-upgrade)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
