#!/bin/sh
# postinst script
case "$1" in
    configure)
        if ! getent group porto >/dev/null; then
            groupadd -g 333 porto 2>/dev/null
            if [ $? -ne 0 ]; then
                echo "Group 'porto' does not create!" >&2
            fi
        fi
    ;;
    upgrade|abort-upgrade)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
