#!/bin/bash

set -x
set -e

# sudo dnf install @development-tools fedora-packager rpmdevtools
# rpmdev-setuptree

rootdir=$(cd $(dirname $0)/../ && pwd)
spec=~/rpmbuild/SPECS/porto.spec

version=$(head -n1 $rootdir/debian/changelog | sed -e 's/[^(]*(\([^)]*\).*/\1/')
version=$(echo $version | cut -d '-' -f 1)
cp $rootdir/spec/porto.spec.in $spec
sed -i -e "s/@VERSION@/$version/" $spec

# create source tar.gz from git repository
pushd $rootdir
git archive --format=tar --prefix=porto/ HEAD | gzip >~/rpmbuild/SOURCES/yandex-porto-${version}.tar.gz
popd
# build package
(cd ~/rpmbuild/SPECS/ && rpmbuild -vv -ba porto.spec)
