#!/bin/sh -x

for u in porto-alice porto-bob porto-charlie porto-david ; do
	id $u && userdel $u
	getent group ${u}-containers && groupdel ${u}-containers
done

# for g in porto porto-containers ; do
#	getent group $g && groupdel $g
# done

