#!/bin/sh

set -ex

: ${COMPRESS=tgz}
: ${NET=NAT}
# ${NET=macvlan eth* eth0; autoconf eth0}
: ${PORTOCTL=portoctl}

L=$(dirname $(dirname $0))/layers

rm -f bootstrap.$COMPRESS
sudo $PORTOCTL build -o bootstrap.$COMPRESS \
	-B $L/bootstrap_ubuntu_xenial.sh \
	-S $L/base_ubuntu_xenial.sh \
	-S $L/common-debootstrap.sh net="$NET"

$PORTOCTL layer -R bootstrap || true
$PORTOCTL layer -I bootstrap bootstrap.$COMPRESS

rm -f ubuntu-precise.$COMPRESS
$PORTOCTL build -l bootstrap -o ubuntu-precise.$COMPRESS \
	-B $L/bootstrap_ubuntu_precise.sh \
	-S $L/base_ubuntu_precise.sh \
	-S $L/common-misc.sh \
	-S $L/common-openssh.sh \
	-S $L/common-devel.sh \
	-S $L/common-cleanup.sh net="$NET"

$PORTOCTL layer -R ubuntu-precise || true
$PORTOCTL layer -I ubuntu-precise ubuntu-precise.$COMPRESS

rm -f ubuntu-xenial.$COMPRESS
$PORTOCTL build -l bootstrap -o ubuntu-xenial.$COMPRESS \
	-B $L/bootstrap_ubuntu_xenial.sh \
	-S $L/base_ubuntu_xenial.sh \
	-S $L/common-misc.sh \
	-S $L/common-openssh.sh \
	-S $L/common-devel.sh \
	-S $L/common-cleanup.sh net="$NET"

$PORTOCTL layer -R ubuntu-xenial || true
$PORTOCTL layer -I ubuntu-xenial ubuntu-xenial.$COMPRESS

rm -f debian-jessie.$COMPRESS
$PORTOCTL build -l bootstrap -o debian-jessie.$COMPRESS \
	-B $L/bootstrap_debian_jessie.sh \
	-S $L/base_debian_jessie.sh \
	-S $L/common-misc.sh \
	-S $L/common-openssh.sh \
	-S $L/common-devel.sh \
	-S $L/common-cleanup.sh net="$NET"

$PORTOCTL layer -R debian-jessie || true
$PORTOCTL layer -I debian-jessie debian-jessie.$COMPRESS

rm -f debian-stretch.$COMPRESS
$PORTOCTL build -l bootstrap -o debian-stretch.$COMPRESS \
	-B $L/bootstrap_debian_stretch.sh \
	-S $L/base_debian_stretch.sh \
	-S $L/common-misc.sh \
	-S $L/common-openssh.sh \
	-S $L/common-devel.sh \
	-S $L/common-cleanup.sh net="$NET"

$PORTOCTL layer -R debian-stretch || true
$PORTOCTL layer -I debian-stretch debian-stretch.$COMPRESS
