#!/bin/bash

SUDO=sudo

$SUDO useradd porto-alice || true
$SUDO usermod -G porto porto-alice || true
$SUDO useradd porto-bob || true
$SUDO usermod -G porto porto-bob || true
$SUDO useradd porto-charlie || true
$SUDO usermod -G porto porto-charlie || true
$SUDO useradd porto-david || true
$SUDO groupadd porto-containers || true
$SUDO usermod -aG porto-containers porto-alice || true
$SUDO groupadd porto-bob-containers || true
$SUDO usermod -aG porto-bob-containers porto-charlie || true
$SUDO usermod -aG porto-bob-containers porto-david || true
$SUDO groupadd porto-alice-group || true
$SUDO usermod -aG porto-alice-group porto-alice || true
#Assuming that porto is already running
