#!/bin/sh

for u in porto-alice porto-bob; do
	id $u 1>/dev/null 2>&1 || useradd $u -G porto
done

id porto-charlie 1>/dev/null 2>&1 || useradd porto-charlie
id porto-david 1>/dev/null 2>&1 || useradd porto-david
