#!/bin/sh

set -e
set -x

ROOTDIR=$(cd $(dirname $0)/../ && pwd)
HOST=${HOST:-lxc-test0}

run() { ssh -4 -t "$HOST" sudo -i "bash -c \"$@\""; }

rsync -4 -av $ROOTDIR ${HOST}:src
run "ln -sf /home/$USER/src/porto/portod /usr/sbin"
run "ln -sf /home/$USER/src/porto/portoctl /usr/sbin"
run "ln -sf /home/$USER/src/porto/portotest /usr/sbin"
run "reload yandex-porto"
sleep 5
run "/home/$USER/src/porto/scripts/test $@"
