#!/bin/sh

set -e

export PATH="/usr/sbin:$PATH"

getver() { portoctl -v 2>&1 | grep $1 | awk '{print $2}'; }
checkver() { [ "$2" = "$3" ] || { echo "Invalid $1 version ($2 != $3)"; }; }

build() {
	version=$(git describe | sed -e 's/^v//')
	dch --newversion $version "teamcity build"
	debuild -i -us -uc -b
	sudo dpkg -i ../yandex-porto_${version}_amd64.deb

	checkver server v$version $(getver server)
	checkver client v$version $(getver client)
}

selftest() {
	sudo scripts/test false true
}

pkgtest() {
	sudo scripts/test pkg
}

stresstest() {
	sudo scripts/test stress
}

[ ! $# -eq 0 ] || set -- build selftest pkgtest stresstest
for f in "$@"; do eval $f; done
