#!/bin/sh

set -e

export PATH="/usr/sbin:$PATH"

getver() { portoctl -v 2>&1 | grep $1 | awk '{print $2}'; }
checkver() { [ "$2" = "$3" ] || { echo "Invalid $1 version ($2 != $3)"; }; }

build() {
	version=$(git describe | sed -e 's/^v//')
	dch --newversion $version "teamcity build"
	find ../ -name '*.deb' -o -name '*.build' -o -name '*.changes' -print0 | xargs -0 rm -f
	debuild -i -us -uc -b
	sudo dpkg -i ../yandex-porto_${version}_amd64.deb

	checkver server v$version $(getver server)
	checkver client v$version $(getver client)
}

selftest() {
	#sudo scripts/test false true
	sudo scripts/test true
}

pkgtest() {
	sudo scripts/test pkg
}

stresstest() {
	sudo scripts/test stress
}

prlog() {
	echo "$1:"
	tail -n 40 $1
}

print_logs() {
	prlog /var/log/portoloop.log
	prlog /var/log/portod.log
}

preparenet() {
	# we need multiple network interfaces for selftest
	sudo ip link del eth9 || :
	sudo ip link add eth9 type dummy
	sudo ip link set dev eth9 up
	sudo ip addr add 192.168.2.2/16 dev eth9
}

fixcg() {
	# make current task belongs to root cgroups
	for cg in /sys/fs/cgroup/*; do
		echo $$ | sudo tee $cg/cgroup.procs &>/dev/null;
	done
}

preparenet
fixcg

[ ! $# -eq 0 ] || set -- build selftest pkgtest stresstest
trap print_logs EXIT
for f in "$@"; do eval $f; done
trap - EXIT
