#!/bin/sh

set -e

HOST=vm

run() { ssh -t "$HOST" sudo -i "bash -c \"$@\""; }
say() { tput setaf 3; echo "$@"; tput sgr0; }

selftest() {
	say "Network: $1"
	run "echo 'network { enabled: $1 dynamic_ifaces: false } container { use_hierarchy: true }' > /etc/portod.conf"
	run portotest
}

stresstest() {
	say "Stress"
	run portotest stress
}

tests="$@"
if [ -z "$tests" ]; then
	tests="false true"
fi

for t in $tests; do
	selftest $t
done

stresstest
