#!/bin/sh

set -e

ROOTDIR=$(cd $(dirname $0)/../ && pwd)

say() { tput setaf 3; echo "$@"; tput sgr0; }

selftest() {
	say "Network: $1"
	echo "network { enabled: $1 dynamic_ifaces: false } container { use_hierarchy: true }" > /etc/portod.conf
	portotest
}

stresstest() {
	say "Stress"
	portotest stress
}

pkgtest() {
	for f in $ROOTDIR/dist/*.conf; do
		$ROOTDIR/scripts/mkimg 5G ${f}.img $f -vT -c $ROOTDIR -C
	done
}

tests="$@"
if [ -z "$tests" ]; then
	tests="false true stress pkg"
fi

for t in $tests; do
	case $t in
		true|false) selftest $t ;;
		stress) stresstest ;;
		pkg) pkgtest ;;
		*) say "Invalid test $t"; exit 1 ;;
	esac
done
