* Что такое Porto?
** Система управления виртуализационными возможностями ядра
** API управлением процессами/контейнерами
* Почему мы не используем альтернативные решения?
** LXC
** lmctfy
** Docker
** libcgroup
* С какими проблемами мы сейчас сталкиваемся?
** Управление сигруппами "размазано" между несколькими сервисами
** libcgroup ненадежен в силу плохого дизайна
** Для эксплуатации сложно управлять взаимозависимыми ручками ядра
** Проблемы с динамическими изменениями конфигурации
* Как мы собираемся их решить?
** Локальный централизованный сервис "настройки" ядра
** Не повторяем ошибки libcgroup
** Концентрируем знания о настройке ядра в Porto
** Сразу поддерживаем live-обновление Porto, закладываем возможности
   динамической конфигурации
* Описание/дизайн Porto
  Porto реализован в виде демона portod; клиенты взаимодействуют с ним с
  помощью protobuf-based API через unix socket. Также предоставляется утилита porto,
  реализующая CLI для ручного управления контейнерами. Для использования в
  автоматическом режиме следуют использовать только API, так как формат вывода и
  возможности утилиты porto могут меняться.
  Основная единица абстракции porto - контейнер. Контейнер однозначно идентифицируется
  именем (уникальность имен - задача клиентов porto), иерархические контейнеры
  не поддерживаются.
  Каждый контейнер описывается свойствами (properties) и данными (data).
  Свойства описывают то, что от контейнера ожидается (проект), а данные описывают
  текущее состояние проекта. Свойства можно изменять, данные можно только считывать.
  Конкретный набор доступных для изменения свойств зависит от текущего
  состояния контейнера, которые описывается данными state.
  Большинство свойств можно изменять только в остановленном состоянии.
  Состояние контейнеров устойчиво по отношению к падениям portod
  (для этого существует демон portoloop который следит и перезапускает portod) и
  клиентов porto, но сбрасывается при перезагрузке машины.

* Планы
** Фаза 1
** Фаза 2
** Фаза 3
** Фаза 4
* Ссылки
  https://wiki.yandex-team.ru/porto
